version: '3.7'

services:
  nestjs-do-scg:
    container_name: nestjs-do-scg
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "6319:3001"
    volumes:
      - .:/usr/src/app
      - ./.env:/usr/src/app/.env:cached
      - /usr/src/app/node_modules
    environment:
      APP_ENV: local
      NODE_ENV: local
    extra_hosts:
      - test-node-js.local:127.0.0.1